// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace EfEnumTest.CompiledModels
{
    public partial class ContextModel
    {
        private ContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("f5dc921f-2c8a-489a-8153-47756418822f"), entityTypeCount: 1)
        {
        }

        partial void Initialize()
        {
            var model = ModelEntityType.Create(this);

            ModelEntityType.CreateAnnotations(model);

            AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);
            AddAnnotation("ProductVersion", "9.0.0");
            AddAnnotation("Relational:MaxIdentifierLength", 63);
        }
    }
}
